name: Bug Report
description: File a bug report
labels: ["Bug"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: textarea
  attributes:
    label: Describe
    description: Describe the issue you are experiencing
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: How can this issue be reproduced?
    placeholder: |
      1. I start a new gitpod instance of...
      2. I execute the command `gpt ...`
      3. See error...
  validations:
    required: false
- type: input
  attributes:
    label: GPT Version
    description: What version of GPT are you using?
    placeholder: 0.4.3
  validations:
    required: true
- type: input
  attributes:
    label: Link to your project
    description: If you have a repo where we can reproduce the error, that would be a great help to find the issue fast.
    placeholder: https://github.com/derroylo/test-repo
- type: textarea
  attributes:
    label: .gpt.yml Content
    description: |
      Paste the content of your .gpt.yml file here, if it is related to the bug.
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Anything else that could help us to fix the issue?

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
