name: Feature Request
description: File a feature request
labels: ["Enhancement"]
body:
- type: textarea
  id: description
  attributes:
    label: Describe the feature you would like to have been added
    description: Describe the feature that you think would make this tool even better. 
  validations:
    required: true
- type: textarea
  id: related-issues
  attributes:
    label: Related issues
    description: Is this feature request related to other issues? If yes, please post them here
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Is there anything else you want to add to this feature request, like images, to make things clearer?
  validations:
    required: false
