name: .NET Core

on: 
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@main
        id: code-analysis
        with:
          project: gitpod-tool.csproj
          build-breaking: false
          all-categories: recommended