name: .NET Core

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -r linux-x64 --configuration Release --no-restore --self-contained false /p:PublishSingleFile=true /p:PublishTrimmed=true
    - name: Zip the Build
      run: cd ./bin/Release/net7.0/linux-x64/ && zip -r ../../../../gitpod-tool.zip ./* && cd -
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        generateReleaseNotes: true
        makeLatest: true
        artifacts: gitpod-tool.zip
        artifactContentType: application/zip
