name: .NET Core

on: 
  push:
    branches:
      - 'feature/*'
      - 'bugfix/*'

jobs:
  tests:
    name: .NET Code Analysis runner
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@main
        id: code-analysis
        with:
          project: gitpod-tool.csproj
          build-breaking: false
          all-categories: recommended
      - name: Upload analysis results
        uses: actions/upload-artifact@v2
        with:
          name: analysis_results.sarif
          path: ${{ steps.code-analysis.outputs.sarifFile }}
